# Generated by Django 3.1.3 on 2020-12-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_registration_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='user',
            new_name='ID',
        ),
    ]
