# Generated by Django 3.1.3 on 2020-12-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20201201_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='ID',
            new_name='user',
        ),
    ]
