# Generated by Django 3.1.3 on 2020-12-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20201201_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='Status',
            field=models.CharField(default='Not downloaded', max_length=200),
        ),
    ]
