# Generated by Django 3.1.3 on 2020-12-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='notify',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
